ALTER TABLE "topics"
  ADD COLUMN "isPreset" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "keywords" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN "refreshCron" VARCHAR(16) NOT NULL DEFAULT '06:00',
  ADD COLUMN "enabled" BOOLEAN NOT NULL DEFAULT true;
