-- Phase 2C — Radar Deep-Dive: 5-field arxiv analysis
--
-- Adds `arxivAnalysis` jsonb column holding the structured summary
-- generated by enrichment_worker._generate_arxiv_analysis(). Patterned
-- after dw-dengwei/daily-arXiv-ai-enhanced's Structure pydantic schema
-- combined with IMRaD conventions:
--
--   {
--     "tldr":        "...",
--     "motivation":  "...",
--     "method":      "...",
--     "result":      "...",
--     "conclusion":  "..."
--   }
--
-- All 5 fields are short (<= 200 chars target, 500 chars hard cap) so
-- the detail card renders them verbatim without runtime truncation.

ALTER TABLE "summaries"
  ADD COLUMN "arxivAnalysis" JSONB;