"""Refresh already-published topics from the latest radar summaries.

This worker deliberately does not discover or publish topics.  It only updates
the candidate set and counters of topics that already exist.  New-topic
proposals are generated by ``topic_proposal_worker`` through its separate
Admin-triggered endpoint.
"""

from __future__ import annotations

import re
from datetime import datetime, timedelta, timezone
from typing import Any
from urllib.parse import urlsplit

from ai_engine.radar.topic_clustering import is_metadata_tag

WINDOW_DAYS = 14
ALLOWED_TIERS = frozenset({"skim", "deep_read"})


def _source_key(url: str, original_kind: str | None) -> str:
    try:
        parsed = urlsplit(url)
        host = (parsed.hostname or "").lower()
        if host.endswith("github.com"):
            owner = next((part for part in parsed.path.split("/") if part), "")
            return f"github:{owner.lower()}" if owner else "github"
        return host or (original_kind or "unknown")
    except ValueError:
        return original_kind or "unknown"


def _topic_terms(name: str) -> set[str]:
    """Use concrete words from a topic name as a conservative fallback."""
    terms = set(re.findall(r"[a-z0-9][a-z0-9-]{2,}|[\u4e00-\u9fff]{2,}", name.lower()))
    return {term for term in terms if not is_metadata_tag(term)}


def _topic_anchor_tags(rows: list[dict[str, Any]], name: str) -> set[str]:
    anchors: set[str] = set()
    for row in rows:
        for raw_tag in row.get("tags") or []:
            tag = str(raw_tag).strip().lower()
            if tag and not is_metadata_tag(tag):
                anchors.add(tag)
    return anchors or _topic_terms(name)


def _matches_topic(summary: dict[str, Any], anchors: set[str]) -> bool:
    tags = {
        str(raw_tag).strip().lower()
        for raw_tag in summary.get("tags") or []
        if not is_metadata_tag(str(raw_tag))
    }
    return bool(tags & anchors)


def _tier(candidate_count: int) -> str:
    if candidate_count >= 6:
        return "hot"
    if candidate_count >= 3:
        return "warming"
    return "emerging"


async def refresh_existing_topics(
    pool: Any,
    *,
    now: datetime | None = None,
) -> dict[str, int]:
    """Refresh candidate links for existing topics only.

    Existing ``admin_manual`` links are preserved.  Automatically-derived
    links outside the rolling window, or no longer meeting summary quality and
    status gates, are removed.  A changed candidate count invalidates the old
    synthesis so the synthesis loop can regenerate it.
    """
    now = now or datetime.now(timezone.utc)
    since = now - timedelta(days=WINDOW_DAYS)

    async with pool.connection() as conn:
        topic_rows = await (
            await conn.execute(
                """
                SELECT t."id", t."name", s."tags"
                FROM "topics" t
                LEFT JOIN "topic_candidates" tc
                  ON tc."topicId" = t."id"
                LEFT JOIN "summaries" s
                  ON s."id" = tc."summaryId"
                GROUP BY t."id", t."name", s."id", s."tags"
                """
            )
        ).fetchall()
        summary_rows = await (
            await conn.execute(
                """
                SELECT "id", "url", "originalKind", "tags"
                FROM "summaries"
                WHERE "status" IN ('candidate', 'published')
                  AND ("publishedAt" >= %s OR "createdAt" >= %s)
                  AND "distilledTier" = ANY(%s)
                  AND ("distilledTotal" IS NULL OR "distilledTotal" >= 0)
                """,
                (since, since, list(ALLOWED_TIERS)),
            )
        ).fetchall()

        grouped: dict[str, dict[str, Any]] = {}
        for row in topic_rows:
            topic_id = str(row["id"])
            topic = grouped.setdefault(
                topic_id, {"name": str(row["name"]), "anchors": set(), "rows": []}
            )
            if row["tags"]:
                topic["rows"].append({"tags": list(row["tags"] or [])})
        for topic in grouped.values():
            topic["anchors"] = _topic_anchor_tags(topic["rows"], topic["name"])

        refreshed = linked = removed = 0
        for topic_id, topic in grouped.items():
            before = await (
                await conn.execute(
                    'SELECT COUNT(*) AS "count" FROM "topic_candidates" WHERE "topicId" = %s',
                    (topic_id,),
                )
            ).fetchone()
            old_count = int(before["count"] if before else 0)

            stale = await conn.execute(
                """
                DELETE FROM "topic_candidates" tc
                USING "summaries" s
                WHERE tc."topicId" = %s
                  AND tc."addedReason" = 'auto'
                  AND tc."summaryId" = s."id"
                  AND NOT (
                    s."status" IN ('candidate', 'published')
                    AND (s."publishedAt" >= %s OR s."createdAt" >= %s)
                    AND s."distilledTier" = ANY(%s)
                  )
                RETURNING tc."id"
                """,
                (topic_id, since, since, list(ALLOWED_TIERS)),
            )
            removed += len(await stale.fetchall())

            for summary in summary_rows:
                if not _matches_topic(dict(summary), topic["anchors"]):
                    continue
                result = await conn.execute(
                    """
                    INSERT INTO "topic_candidates"
                      ("id", "topicId", "summaryId", "addedReason", "addedAt")
                    VALUES (gen_random_uuid(), %s, %s, 'auto', now())
                    ON CONFLICT ("topicId", "summaryId") DO NOTHING
                    RETURNING "id"
                    """,
                    (topic_id, str(summary["id"])),
                )
                if await result.fetchone():
                    linked += 1

            rows = await (
                await conn.execute(
                    """
                    SELECT s."url", s."originalKind"
                    FROM "topic_candidates" tc
                    JOIN "summaries" s ON s."id" = tc."summaryId"
                    WHERE tc."topicId" = %s
                    """,
                    (topic_id,),
                )
            ).fetchall()
            count = len(rows)
            source_count = len({_source_key(str(row["url"]), row["originalKind"]) for row in rows})
            await conn.execute(
                """
                UPDATE "topics"
                SET "candidateCount" = %s, "sourceCount" = %s, "tier" = %s,
                    "lastSyncedAt" = now(), "aggregationWindowStart" = %s,
                    "aggregationWindowEnd" = %s,
                    "synthesisPayload" = CASE WHEN %s <> %s THEN NULL ELSE "synthesisPayload" END,
                    "synthesisGeneratedAt" = CASE WHEN %s <> %s THEN NULL ELSE "synthesisGeneratedAt" END,
                    "updatedAt" = now()
                WHERE "id" = %s
                """,
                (count, source_count, _tier(count), since, now, count, old_count,
                 count, old_count, topic_id),
            )
            refreshed += 1

    return {"topics_refreshed": refreshed, "candidates_linked": linked, "candidates_removed": removed}


__all__ = ["refresh_existing_topics"]
