// 错误码契约。完整定义见 docs/contracts/error-codes.md。
// 这里只列 P0 必带的最小集合。

/** HTTP 状态码统一映射 */
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  GONE: 410,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

/** 业务错误码（按 docs/contracts/error-codes.md 维护） */
export const ERROR_CODES = {
  // Auth / 权限
  AUTH_NOT_AUTHENTICATED: 'AUTH_NOT_AUTHENTICATED',
  AUTH_DOMAIN_NOT_ALLOWED: 'AUTH_DOMAIN_NOT_ALLOWED',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // 草稿 / 发布
  DRAFT_NOT_FOUND: 'DRAFT_NOT_FOUND',
  DRAFT_NOT_OWNER: 'DRAFT_NOT_OWNER',
  DRAFT_ALREADY_PUBLISHED: 'DRAFT_ALREADY_PUBLISHED',

  // AI 调研
  AI_ENGINE_UNAVAILABLE: 'AI_ENGINE_UNAVAILABLE',
  AI_QUOTA_EXCEEDED: 'AI_QUOTA_EXCEEDED',
  AI_INVALID_SOURCE_POLICY: 'AI_INVALID_SOURCE_POLICY',
  AI_SOURCE_NOT_VISIBLE: 'AI_SOURCE_NOT_VISIBLE',
  AI_IDEMPOTENCY_MISMATCH: 'AI_IDEMPOTENCY_MISMATCH',
  AI_JOB_NOT_FOUND: 'AI_JOB_NOT_FOUND',
  AI_JOB_NOT_CANCELLABLE: 'AI_JOB_NOT_CANCELLABLE',

  // AI 多轮追问
  AI_CHAT_SEED_NOT_FOUND: 'AI_CHAT_SEED_NOT_FOUND',
  AI_CHAT_FORBIDDEN_SEED: 'AI_CHAT_FORBIDDEN_SEED',
  AI_CHAT_SESSION_NOT_FOUND: 'AI_CHAT_SESSION_NOT_FOUND',
  AI_CHAT_CONTENT_TOO_LONG: 'AI_CHAT_CONTENT_TOO_LONG',
  AI_CHAT_SESSION_CLOSED: 'AI_CHAT_SESSION_CLOSED',

  // 文件导入 / URL 抓取
  IMPORT_FILE_TOO_LARGE: 'IMPORT_FILE_TOO_LARGE',
  IMPORT_INVALID_MIME: 'IMPORT_INVALID_MIME',
  IMPORT_NOT_UTF8: 'IMPORT_NOT_UTF8',
  IMPORT_HTML_UNSAFE: 'IMPORT_HTML_UNSAFE',
  IMPORT_HASH_DUPLICATE: 'IMPORT_HASH_DUPLICATE',

  URL_FETCH_BLOCKED: 'URL_FETCH_BLOCKED',
  URL_FETCH_TIMEOUT: 'URL_FETCH_TIMEOUT',
  URL_FETCH_TOO_LARGE: 'URL_FETCH_TOO_LARGE',
  URL_REDIRECT_LIMIT: 'URL_REDIRECT_LIMIT',

  // 评论 / 提名
  COMMENT_TARGET_INVALID: 'COMMENT_TARGET_INVALID',
  COMMENT_SELF_STAR_FORBIDDEN: 'COMMENT_SELF_STAR_FORBIDDEN',
  COMMENT_ALREADY_NOMINATED: 'COMMENT_ALREADY_NOMINATED',

  // Admin
  ADMIN_QUEUE_EMPTY: 'ADMIN_QUEUE_EMPTY',
  ADMIN_NOT_ENOUGH_ADMINS: 'ADMIN_NOT_ENOUGH_ADMINS',
  ADMIN_ACTION_REQUIRES_CONFIRM: 'ADMIN_ACTION_REQUIRES_CONFIRM',

  // Worker
  WORKER_LEASE_LOST: 'WORKER_LEASE_LOST',
  WORKER_TIMEOUT: 'WORKER_TIMEOUT',
  WORKER_RETRY_EXHAUSTED: 'WORKER_RETRY_EXHAUSTED',

  // 通用
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL: 'INTERNAL',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** BFF 统一错误响应 */
export interface ApiError {
  code: ErrorCode;
  message: string;        // 用户可读（已脱敏）
  requestId: string;      // 服务端日志关联
  details?: unknown;      // 仅开发模式允许堆栈
}
