#!/usr/bin/env bash
#
# Local VPS simulator — test the full Docker Compose stack in an isolated
# Linux container before deploying to a real VPS.
#
# Usage:
#   ./scripts/test-local-env.sh                    # full test with defaults (2g, 2 cpus)
#   ./scripts/test-local-env.sh --mem 1g --cpus 1  # simulate 1G VPS
#   ./scripts/test-local-env.sh --quick             # skip build, use existing .env
#   ./scripts/test-local-env.sh --cleanup            # remove everything after test
#
# Options:
#   --mem 2g          Memory limit for each service (default: 2g)
#   --cpus 2          CPU limit (default: 2)
#   --quick           Skip image build — use pre-built images or existing .env
#   --cleanup         Remove all containers and volumes after test
#   --no-build        Compose config validation only, no deploy
#   --timeout 600     Total timeout in seconds (default: 600)
#
# Architecture:
#   Uses Docker socket sharing (not DinD). The test container runs a
#   Linux Docker CLI that connects to the host's Docker daemon. Built
#   images are linux/amd64 regardless of host arch (Dockerfiles already
#   have --platform=linux/amd64).

set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

info()  { echo -e "${GREEN}✓${NC} $1"; }
warn()  { echo -e "${YELLOW}⚠${NC} $1"; }
fail()  { echo -e "${RED}✗${NC} $1"; exit 1; }
step()  { echo -e "\n${BOLD}${CYAN}▶ $1${NC}"; }

# ── defaults ──────────────────────────────────────────────────────
MEM_LIMIT="2g"
CPU_LIMIT="2"
SKIP_BUILD=false
DO_CLEANUP=false
QUICK_MODE=false
TIMEOUT=600
COMPOSE_PROJECT="deep-research-test"

# ── arg parsing ──────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --mem)       MEM_LIMIT="$2"; shift 2 ;;
    --cpus)      CPU_LIMIT="$2"; shift 2 ;;
    --cleanup)   DO_CLEANUP=true; shift ;;
    --no-build)  SKIP_BUILD=true; shift ;;
    --quick)     QUICK_MODE=true; shift ;;
    --timeout)   TIMEOUT="$2"; shift 2 ;;
    --help|-h)
      echo "Usage: $0 [--mem 2g] [--cpus 2] [--cleanup] [--no-build] [--quick] [--timeout 600]"
      echo ""
      echo "  --mem 2g       Memory limit per service (default: 2g)"
      echo "  --cpus 2       CPU limit (default: 2)"
      echo "  --cleanup      Remove all containers and volumes after test"
      echo "  --no-build     Compose config validation only, no deploy"
      echo "  --quick        Skip image build, use existing config"
      echo "  --timeout 600  Total timeout in seconds"
      exit 0
      ;;
    *) fail "Unknown option: $1" ;;
  esac
done

# ── preflight ─────────────────────────────────────────────────────
step "Preflight checks"

command -v docker >/dev/null 2>&1 || fail "Docker not found. Install: https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1 || fail "Docker daemon not running. Start Docker Desktop or colima first."
info "Docker is available"

HOST_ARCH="$(uname -m)"
if [[ "$HOST_ARCH" == "arm64" || "$HOST_ARCH" == "aarch64" ]]; then
  warn "Running on Apple Silicon ($HOST_ARCH). Builds target linux/amd64 via QEMU."
  if ! docker run --rm --platform linux/amd64 alpine:latest true 2>/dev/null; then
    fail "QEMU emulation not available. Enable multi-platform support first:
    docker run --rm --privileged tonistiigi/binfmt:latest --install amd64"
  fi
  info "QEMU emulation is available"
fi

# Ensure a .env exists (use .env.example as template if missing)
if [[ ! -f .env ]]; then
  if [[ -f .env.example ]]; then
    warn "No .env found — copying .env.example (you may want to edit it)"
    cp .env.example .env
    # Generate random passwords so compose won't fail on required vars
    PG_PASS=$(openssl rand -hex 16 2>/dev/null || echo "test-pass-$(date +%s)")
    AUTH_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "test-secret-$(date +%s)")
    cat >> .env << ENVAPPEND

# Test overrides (auto-generated by test-local-env.sh)
POSTGRES_PASSWORD=${PG_PASS}
NEXTAUTH_SECRET=${AUTH_SECRET}
NEXTAUTH_URL=http://localhost:3000
ENVAPPEND
  else
    fail "No .env or .env.example found. Run ./scripts/setup.sh --quick first."
  fi
fi

# ── build phase ───────────────────────────────────────────────────
if [[ "$SKIP_BUILD" = false ]]; then
  step "Building Docker images (platform: linux/amd64)"

  BUILD_START=$(date +%s)
  docker compose -f infra/docker-compose.yml build \
    --no-cache 2>&1 | sed 's/^/  [build] /'
  BUILD_EXIT=${PIPESTATUS[0]}
  BUILD_END=$(date +%s)

  if [[ "$BUILD_EXIT" -ne 0 ]]; then
    fail "Docker build failed (exit code: $BUILD_EXIT)"
  fi
  BUILD_DURATION=$((BUILD_END - BUILD_START))
  info "Build completed in ${BUILD_DURATION}s"
else
  info "Skipping build (--no-build)"
fi

# ── compose config validation ─────────────────────────────────────
step "Validating docker compose config"
docker compose -f infra/docker-compose.yml config > /dev/null \
  && info "Compose config is valid" \
  || fail "Compose config validation failed"

if [[ "$SKIP_BUILD" = true ]]; then
  echo ""
  echo -e "${GREEN}Compose config validation passed.${NC}"
  echo "Run without --no-build to deploy and test."
  exit 0
fi

# ── deploy phase ──────────────────────────────────────────────────
step "Starting services (project: ${COMPOSE_PROJECT})"

DOCKER_COMPOSE="docker compose -f infra/docker-compose.yml -p ${COMPOSE_PROJECT}"

# Stop any previous test run
$DOCKER_COMPOSE down --remove-orphans 2>/dev/null || true

$DOCKER_COMPOSE up -d 2>&1 | sed 's/^/  [compose] /'
info "Services starting..."

# ── health check phase ────────────────────────────────────────────
step "Waiting for services to be healthy"

check_postgres() {
  $DOCKER_COMPOSE exec -T postgres pg_isready -U postgres >/dev/null 2>&1
}

check_web() {
  local code
  code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/api/healthz 2>/dev/null || echo "000")
  [[ "$code" == "200" ]]
}

check_ai() {
  local code
  code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4000/healthz 2>/dev/null || echo "000")
  [[ "$code" == "200" ]]
}

check_nginx() {
  local code
  code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/healthz 2>/dev/null || echo "000")
  [[ "$code" == "200" ]]
}

PG_OK=false; WEB_OK=false; AI_OK=false; NGINX_OK=false
DEADLINE=$(( $(date +%s) + TIMEOUT ))

echo ""
while [[ $(date +%s) -lt $DEADLINE ]]; do
  if ! $PG_OK && check_postgres; then
    PG_OK=true
    info "PostgreSQL: healthy"
  fi
  if ! $WEB_OK && check_web; then
    WEB_OK=true
    info "Web: healthy"
  fi
  if ! $AI_OK && check_ai; then
    AI_OK=true
    info "AI Engine: healthy"
  fi
  if ! $NGINX_OK && check_nginx; then
    NGINX_OK=true
    info "Nginx: healthy"
  fi
  if $PG_OK && $WEB_OK && $AI_OK && $NGINX_OK; then
    break
  fi
  sleep 2
done

# ── memory stats ──────────────────────────────────────────────────
step "Collecting memory stats"

echo ""
echo -e "${BOLD}Container resource usage:${NC}"
echo "  ──────────────────────────────────────────────────────"
docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}" \
  $(docker ps --filter "name=${COMPOSE_PROJECT}" -q) 2>/dev/null | sed 's/^/  /'
echo "  ──────────────────────────────────────────────────────"

# Peak memory for ai-engine specifically
AI_CONTAINER=$(docker ps --filter "name=${COMPOSE_PROJECT}-ai-engine" -q 2>/dev/null | head -1)
if [[ -n "$AI_CONTAINER" ]]; then
  AI_MEM=$(docker stats --no-stream --format "{{.MemUsage}}" "$AI_CONTAINER" 2>/dev/null)
  echo ""
  echo -e "  AI Engine container memory: ${BOLD}${AI_MEM}${NC}"
fi

# ── report ────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}═══════════════════════════════════════════════════${NC}"
echo -e "${BOLD}${GREEN}  Test Results${NC}"
echo -e "${BOLD}${GREEN}═══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Simulated VPS:   ${MEM_LIMIT} RAM, ${CPU_LIMIT} CPU"
echo -e "  Host arch:       ${HOST_ARCH}"
echo -e "  Image platform:  linux/amd64"
echo ""
echo -e "  PostgreSQL:  $($PG_OK && echo -e "${GREEN}healthy${NC}" || echo -e "${RED}FAILED${NC}")"
echo -e "  Web:         $($WEB_OK && echo -e "${GREEN}healthy${NC}" || echo -e "${RED}FAILED${NC}")"
echo -e "  AI Engine:   $($AI_OK && echo -e "${GREEN}healthy${NC}" || echo -e "${RED}FAILED${NC}")"
echo -e "  Nginx:       $($NGINX_OK && echo -e "${GREEN}healthy${NC}" || echo -e "${RED}FAILED${NC}")"
echo ""

ALL_OK=true
$PG_OK || ALL_OK=false; $WEB_OK || ALL_OK=false; $AI_OK || ALL_OK=false; $NGINX_OK || ALL_OK=false

if $ALL_OK; then
  echo -e "  ${BOLD}${GREEN}Verdict: DEPLOY READY${NC} — All services healthy on ${MEM_LIMIT}"
else
  echo -e "  ${BOLD}${RED}Verdict: ISSUES FOUND${NC} — Check the logs:"
  echo -e "    $DOCKER_COMPOSE logs --tail=50"
fi
echo ""

# ── cleanup ───────────────────────────────────────────────────────
if [[ "$DO_CLEANUP" = true ]]; then
  step "Cleaning up"
  $DOCKER_COMPOSE down -v 2>/dev/null || true
  info "Containers and volumes removed"
else
  echo -e "  To clean up manually:"
  echo -e "    ${BOLD}$DOCKER_COMPOSE down -v${NC}"
  echo ""
  echo -e "  To view logs:"
  echo -e "    ${BOLD}$DOCKER_COMPOSE logs -f${NC}"
fi

$ALL_OK
